### ISSUE TITLE
정적페이지의 about page

### ISSUE THREAD

**Issue by jihye0** [20-2-SKKU-OSS/2020-2-OSS-5#14]
정적 페이지의 about page를 저희 프로젝트에 맞게 바꿔야 할 것 같습니다.

**Comment by Jungseoyeon** [comment]
네 좋은생각입니다.

**Comment by jihye0** [comment]
제가 github repository 링크를 저희 github link로 바꾸겠습니다.

**Comment by Brian-Hwang** [comment]
about.md 2차 update 했습니다

**Comment by Jungseoyeon** [comment]
@Brian-Hwang 
어떤 부분을 업데이트하셨는지 궁금합니다. 
또 업데이트 하기전에 지혜와 제가 바꾸어놓은 부분이 다시 전으로 돌아갔습니다. 
그리고 제목이 왜 Brian-Hwang's page인지 궁금합니다.

**Comment by Brian-Hwang** [comment]
@Jungseoyeon 아 제 개인 static page 참고해서 하다가 섞인것 같네요 고치겠습니다 ㅜ

**Comment by Brian-Hwang** [comment]
About.md 완료하였습니다.
더 추가 개선 사항 있으시면 알려주세요!
