### ISSUE TITLE
[W13] 회의

### ISSUE THREAD

**Issue by Na-Hyeon-Oh** [20-2-SKKU-OSS/2020-2-OSS-5#17]
- [ ] 추가적인 commit 필요하다면 commit

- [ ] **이번 주 회의 결과도 정리해서 업로드하면 좋을 것 같습니다**

- [ ] 개발 과정에서 **사용한 브랜치**들도 정리하면 좋을 것 같아요 ( ex) 오나현 ONH )

확인하시면 스티커나 commet 부탁드려요.

### 역할 분배
자료 정리 - 이다윤 조현수 황준용
PPT 제작 - 임지혜 정서연
발표 영상 촬영 - 오나현

**Comment by leedayun** [comment]
브랜치로 따로 안하고 메인에 바로 커밋했는데 지금 올리는 것부터 브랜치 생성해서 merge 하도록 하겠습니다

**Comment by jihye0** [comment]
네 확인하였습니다.

**Comment by Jungseoyeon** [comment]
네 확인하였습니다. 이대로 진행하겠습니다.
