### ISSUE TITLE
Wiki Page update

### ISSUE THREAD

**Issue by leedayun** [20-2-SKKU-OSS/2020-2-OSS-5#32]
위키페이지 업데이트&튜토리얼 추가 부탁드립니다~
현재 결과 부분, 보완점 부분 업데이트 안되어 있습니다.
결과부분에 어떻게 조절할 수 있는지 튜토리얼 넣으면 될 것 같습니다.

**Comment by Brian-Hwang** [comment]
넵 post 완료되는데로 참고하여 Wiki Page 작성하겠습니다~
