### ISSUE TITLE
최종 결과 Post Update

### ISSUE THREAD

**Issue by leedayun** [20-2-SKKU-OSS/2020-2-OSS-5#33]
최종결과 및 보완점 부분 정적페이지에 아직 안올라와 있습니다.
결과 내용 확인하시고 정적페이지에 포스트해주세요

First goal: 색 커스텀, 사용자가 원하는 색 골라서 커스텀할 수 있도록 만들기
Achieved: 코드상에서 색상 범위 다양화, 색상 이름 추가
Developing : UI상에서 사용자가 원하는 색을 선택할 수 있도록 하는 기능, 색상 픽커 혹은 프리셋을 UI상에서 띄우도록 하는 기능
Second goal: 스트로크 너비 설정, 디폴트인 스트로크 너비를 사용자가 커스텀할 수 있도록
Achieved: 기존 디폴트 값이던 호의 크기를 조절하여 버튼의 색을 더 잘 볼 수 있도록 하고 호의 크기를 키워 버튼 반지름을 키워 버튼의 크기를 키움.
Developing: 버튼을 눌렀을 때 다양한 호와 반지름 사이즈의 프리셋 버튼을 제공하여 사용자가 선택할 수 있도록 하는 기능.

**Comment by ChoHyeonSu** [comment]
올라온 자료 확인했습니다. 바로 진행하겠습니다

**Comment by Na-Hyeon-Oh** [comment]
@ChoHyeonSu commit이 잘 되지 않은 것 같은데 확인해보실래요?
