### ISSUE TITLE
13주차 개인 기여도 추가

### ISSUE THREAD

**Issue by leedayun** [20-2-SKKU-OSS/2020-2-OSS-5#34]
최종보고서를 준비하면서, 또한 깃헙페이지 최종 정리하면서
 어제 밤까지 올렸던 것 외에 추가로 더 기여한 부분이 있으시다면 
post의 13주차 Contribution 각자 커밋해주시길 바랍니다!

**Comment by leedayun** [comment]
제 경우 README.md 파일 업데이트, ABOUT.md 파일 업데이트, 정적페이지 추가 및 보완, 최종발표 자료정리 등을 추가로 커밋해놨습니다. 다른 분들 ppt나 이런건 제가 임의로 각자 역할 올려놨는데 원하시면 수정 및 추가해주세요~

**Comment by Na-Hyeon-Oh** [comment]
확인했습니다 !

**Comment by Brian-Hwang** [comment]
Commit 했습니다!

**Comment by Jungseoyeon** [comment]
확인했습니다.
