### ISSUE TITLE
Button 너비 관련해서 divider 값 재확인

### ISSUE THREAD

**Issue by Na-Hyeon-Oh** [20-2-SKKU-OSS/2020-2-OSS-5#8]
divider 확인 다시 부탁드립니다 !

**Comment by jihye0** [comment]
네. 우선 제가 고친 것이 틀린 것 같아서 다시 되돌려 놓겠습니다. 
ondraw 함수에서 centerX와 centerY 를 건들이는 것이 아닌 것 같아요.

**Comment by Jungseoyeon** [comment]
centerX와 centerY는 좌표같다는 생각이 듭니다.

**Comment by jihye0** [comment]
onDraw 함수에서 radius의 값을 바꾸면 될 것 같습니다.

**Comment by Jungseoyeon** [comment]
radius에서 0.5를 빼는건 어떨까요?

**Comment by jihye0** [comment]
네 좋습니다.

**Comment by jihye0** [comment]
radius 값이 너무 작은 것 같습니다.
0.25를 빼보겠습니다.

**Comment by Jungseoyeon** [comment]
좋은 생각인것 같습니다.

**Comment by jihye0** [comment]
mMainCircleRadius  변수를 봐야할 것 같습니다.

**Comment by jihye0** [comment]
dimens.xml 에 있는 default 값을 변경하는 것으로 개발 방향을 바꾸었습니다.
